version: '3'

services:
  etcd:
    image: gcr.io/etcd-development/etcd:v3.4.34
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - "2379:2379"
    command: >
      /usr/local/bin/etcd
      --name etcd0
      --data-dir /etcd-data
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://etcd:2379
    volumes:
      - etcd-data:/etcd-data

  coredns:
    image: coredns/coredns:1.11.3
    container_name: coredns
    depends_on:
      - etcd
    volumes:
      - ./Corefile:/Corefile
    ports:
      - "1053:1053/udp"
      - "1053:1053/tcp"
    command: -conf /Corefile -dns.port 1053

volumes:
  etcd-data:
